In [25]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import Normalizer
from sklearn.compose import ColumnTransformer
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import InputLayer
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

In [3]:
dataset = pd.read_csv('life_expectancy.csv')
dataset.head()

,Country,Year,Status,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,...,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling,Life expectancy
0,Afghanistan,2015,Developing,263.0,62,0.01,71.279624,65.0,1154,19.1,...,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1,65.0
1,Afghanistan,2014,Developing,271.0,64,0.01,73.523582,62.0,492,18.6,...,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0,59.9
2,Afghanistan,2013,Developing,268.0,66,0.01,73.219243,64.0,430,18.1,...,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9,59.9
3,Afghanistan,2012,Developing,272.0,69,0.01,78.184215,67.0,2787,17.6,...,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8,59.5
4,Afghanistan,2011,Developing,275.0,71,0.01,7.097109,68.0,3013,17.2,...,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5,59.2

In [4]:
dataset.describe()

,Year,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,under-five deaths,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling,Life expectancy
count,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2.938000e+03,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000
mean,2007.518720,164.725664,30.303948,4.546875,738.251295,83.022124,2419.592240,38.381178,42.035739,82.617767,5.924098,82.393125,1.742103,6611.523863,1.023085e+07,4.821886,4.852144,0.630362,12.009837,69.234717
std,4.613841,124.086215,117.926501,3.921946,1987.914858,22.996984,11467.272489,19.935375,160.445548,23.367166,2.400770,23.655562,5.077785,13296.603449,5.402242e+07,4.397621,4.485854,0.205140,3.265139,9.509115
min,2000.000000,1.000000,0.000000,0.010000,0.000000,1.000000,0.000000,1.000000,0.000000,3.000000,0.370000,2.000000,0.100000,1.681350,3.400000e+01,0.100000,0.100000,0.000000,0.000000,36.300000
25%,2004.000000,74.000000,0.000000,1.092500,4.685343,82.000000,0.000000,19.400000,0.000000,78.000000,4.370000,78.000000,0.100000,580.486996,4.189172e+05,1.600000,1.600000,0.504250,10.300000,63.200000
50%,2008.000000,144.000000,3.000000,3.755000,64.912906,92.000000,17.000000,43.500000,4.000000,93.000000,5.755000,93.000000,0.100000,1766.947595,1.386542e+06,3.300000,3.300000,0.677000,12.300000,72.100000
75%,2012.000000,227.000000,22.000000,7.390000,441.534144,96.000000,360.250000,56.100000,28.000000,97.000000,7.330000,97.000000,0.800000,4779.405190,4.584371e+06,7.100000,7.200000,0.772000,14.100000,75.600000
max,2015.000000,723.000000,1800.000000,17.870000,19479.911610,99.000000,212183.000000,87.300000,2500.000000,99.000000,17.600000,99.000000,50.600000,119172.741800,1.293859e+09,27.700000,28.600000,0.948000,20.700000,89.000000

In [5]:
dataset = dataset.drop(['Country'], axis=1)

## Select features and labels

In [6]:
features = dataset.iloc[:, :-2]
labels = dataset.iloc[:, -1]

In [7]:
features

,Year,Status,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,under-five deaths,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources
0,2015,Developing,263.0,62,0.01,71.279624,65.0,1154,19.1,83,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479
1,2014,Developing,271.0,64,0.01,73.523582,62.0,492,18.6,86,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476
2,2013,Developing,268.0,66,0.01,73.219243,64.0,430,18.1,89,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470
3,2012,Developing,272.0,69,0.01,78.184215,67.0,2787,17.6,93,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463
4,2011,Developing,275.0,71,0.01,7.097109,68.0,3013,17.2,97,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2933,2004,Developing,723.0,27,4.36,0.000000,68.0,31,27.1,42,67.0,7.13,65.0,33.6,454.366654,12777511.0,9.4,9.4,0.407
2934,2003,Developing,715.0,26,4.06,0.000000,7.0,998,26.7,41,7.0,6.52,68.0,36.7,453.351155,12633897.0,9.8,9.9,0.418
2935,2002,Developing,73.0,25,4.43,0.000000,73.0,304,26.3,40,73.0,6.53,71.0,39.8,57.348340,125525.0,1.2,1.3,0.427
2936,2001,Developing,686.0,25,1.72,0.000000,76.0,529,25.9,39,76.0,6.16,75.0,42.1,548.587312,12366165.0,1.6,1.7,0.427
2937,2000,Developing,665.0,24,1.68,0.000000,79.0,1483,25.5,39,78.0,7.10,78.0,43.5,547.358879,12222251.0,11.0,11.2,0.434

## Encode categorical columns

In [8]:
features = pd.get_dummies(features)
features = features.iloc[:, :-1]

features.head()

,Year,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,under-five deaths,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Status_Developed
0,2015,263.0,62,0.01,71.279624,65.0,1154,19.1,83,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,0
1,2014,271.0,64,0.01,73.523582,62.0,492,18.6,86,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,0
2,2013,268.0,66,0.01,73.219243,64.0,430,18.1,89,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,0
3,2012,272.0,69,0.01,78.184215,67.0,2787,17.6,93,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,0
4,2011,275.0,71,0.01,7.097109,68.0,3013,17.2,97,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,0

In [9]:
# change status developed col dtype to int64
features.Status_Developed = features.Status_Developed.astype('int64')

In [10]:
features.dtypes

Year                                 int64
Adult Mortality                    float64
infant deaths                        int64
Alcohol                            float64
percentage expenditure             float64
Hepatitis B                        float64
Measles                              int64
 BMI                               float64
under-five deaths                    int64
Polio                              float64
Total expenditure                  float64
Diphtheria                         float64
 HIV/AIDS                          float64
GDP                                float64
Population                         float64
 thinness  1-19 years              float64
 thinness 5-9 years                float64
Income composition of resources    float64
Status_Developed                     int64
dtype: object

## Split data into train-test

In [11]:
features_train, features_test, labels_train, labels_test = train_test_split(features, labels, test_size = 0.20, random_state=0)

## Standardize Data

In [12]:
numerical_features = features.select_dtypes(include=['float64', 'int64'])
numerical_columns = numerical_features.columns
ct = ColumnTransformer([("only numeric", StandardScaler(), numerical_columns)], remainder='passthrough')

In [19]:
features_train_scaled = ct.fit_transform(features_train)
features_test_scaled = ct.transform(features_test)

(2938, 19)

## Implementing Deep Learning

In [24]:
# initialize model obj
my_model = Sequential()

# create input layer with shape of number of features
input = InputLayer(input_shape = (features.shape[1], ))
my_model.add(input)

# add hidden layer with 64 units
my_model.add(Dense(64, activation = "relu"))

# add one output layer with 1 output
my_model.add(Dense(1))

# summary of model
my_model.summary()

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_3 (Dense)              (None, 64)                1280
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 65
=================================================================
Total params: 1,345
Trainable params: 1,345
Non-trainable params: 0
_________________________________________________________________

## Initializing the optimizer and compiling the model

In [29]:
# Create an instance of the Adam optimizer with the learning rate equal to 0.01
opt = Adam(learning_rate = 0.01)

#  compile the model
my_model.compile(loss = 'mse', metrics = ['mae'], optimizer = opt)

# Fit and evaluate the model
my_model.fit(features_train_scaled, labels_train, epochs = 40, batch_size = 1, verbose = 1)

Epoch 1/40
2350/2350 [==============================] - 1s 519us/step - loss: 176.8182 - mae: 7.6071
Epoch 2/40
2350/2350 [==============================] - 1s 510us/step - loss: 29.6930 - mae: 3.9211
Epoch 3/40
2350/2350 [==============================] - 1s 533us/step - loss: 22.2959 - mae: 3.5525
Epoch 4/40
2350/2350 [==============================] - 1s 522us/step - loss: 26.1824 - mae: 3.33150s - loss:
Epoch 5/40
2350/2350 [==============================] - 1s 515us/step - loss: 20.3007 - mae: 3.2427
Epoch 6/40
2350/2350 [==============================] - 1s 514us/step - loss: 18.1114 - mae: 3.01350s - loss: 1
Epoch 7/40
2350/2350 [==============================] - 1s 524us/step - loss: 15.5313 - mae: 2.8896
Epoch 8/40
2350/2350 [==============================] - 1s 527us/step - loss: 14.2307 - mae: 2.8037
Epoch 9/40
2350/2350 [==============================] - 1s 526us/step - loss: 18.5225 - mae: 2.7747
Epoch 10/40
2350/2350 [==============================] - 1s 556us/step - loss: 13.7849 - mae: 2.6449
Epoch 11/40
2350/2350 [==============================] - 1s 529us/step - loss: 12.3187 - mae: 2.60690s - loss: 12.3398 - mae: 2.
Epoch 12/40
2350/2350 [==============================] - 1s 550us/step - loss: 22.8553 - mae: 2.8186
Epoch 13/40
2350/2350 [==============================] - 1s 532us/step - loss: 11.3455 - mae: 2.46190s - loss: 9.7032 -
Epoch 14/40
2350/2350 [==============================] - 1s 535us/step - loss: 15.6283 - mae: 2.6830
Epoch 15/40
2350/2350 [==============================] - 1s 528us/step - loss: 11.6031 - mae: 2.4557
Epoch 16/40
2350/2350 [==============================] - 1s 516us/step - loss: 10.7521 - mae: 2.4182
Epoch 17/40
2350/2350 [==============================] - 1s 517us/step - loss: 12.2859 - mae: 2.4773
Epoch 18/40
2350/2350 [==============================] - 1s 530us/step - loss: 12.3526 - mae: 2.5150
Epoch 19/40
2350/2350 [==============================] - 1s 512us/step - loss: 12.3039 - mae: 2.3686
Epoch 20/40
2350/2350 [==============================] - 1s 509us/step - loss: 9.8492 - mae: 2.3218
Epoch 21/40
2350/2350 [==============================] - 1s 537us/step - loss: 11.8877 - mae: 2.3771
Epoch 22/40
2350/2350 [==============================] - 1s 509us/step - loss: 9.2546 - mae: 2.2247
Epoch 23/40
2350/2350 [==============================] - 1s 524us/step - loss: 9.9189 - mae: 2.3165
Epoch 24/40
2350/2350 [==============================] - 1s 514us/step - loss: 11.1527 - mae: 2.32480s - loss: 11.4532 - mae
Epoch 25/40
2350/2350 [==============================] - 1s 533us/step - loss: 9.9462 - mae: 2.2723
Epoch 26/40
2350/2350 [==============================] - 1s 517us/step - loss: 8.8532 - mae: 2.1783
Epoch 27/40
2350/2350 [==============================] - 1s 542us/step - loss: 8.6419 - mae: 2.1921 1s - los
Epoch 28/40
2350/2350 [==============================] - 1s 510us/step - loss: 12.6635 - mae: 2.3544
Epoch 29/40
2350/2350 [==============================] - 1s 516us/step - loss: 8.6559 - mae: 2.1506
Epoch 30/40
2350/2350 [==============================] - 1s 518us/step - loss: 8.4434 - mae: 2.1604
Epoch 31/40
2350/2350 [==============================] - 1s 514us/step - loss: 8.7263 - mae: 2.1486
Epoch 32/40
2350/2350 [==============================] - 1s 519us/step - loss: 10.1953 - mae: 2.2190
Epoch 33/40
2350/2350 [==============================] - 1s 528us/step - loss: 8.2270 - mae: 2.0643
Epoch 34/40
2350/2350 [==============================] - 1s 515us/step - loss: 9.8952 - mae: 2.2072
Epoch 35/40
2350/2350 [==============================] - 1s 524us/step - loss: 7.5084 - mae: 2.0430 0s - loss: 7.5305 -
Epoch 36/40
2350/2350 [==============================] - 1s 523us/step - loss: 9.0577 - mae: 2.1568 0s - loss: 8.2050 - mae:
Epoch 37/40
2350/2350 [==============================] - 1s 524us/step - loss: 8.2479 - mae: 2.0774
Epoch 38/40
2350/2350 [==============================] - 1s 528us/step - loss: 7.6909 - mae: 2.0786
Epoch 39/40
2350/2350 [==============================] - 1s 527us/step - loss: 8.3912 - mae: 2.1069
Epoch 40/40
2350/2350 [==============================] - 1s 514us/step - loss: 8.3377 - mae: 2.0761

In [30]:
# testing model
res_mse , res_mae = my_model.evaluate(features_test_scaled, labels_test, verbose = 0)
print(res_mse, res_mae)

8.559435844421387 2.182018995285034